pipeline {
  agent any
  tools {
    nodejs "11.14.0"
  }
  stages {
		stage('node test') {
      steps {
        sh 'node -v'
      }
    }
    stage('docker test') {
      steps {
        sh 'docker --version'
      }
    }
    stage('build') {
      steps {
        script {
          docker.build("-f ./deployfiles")
        }
      }
    }
    stage('deploy') {
      steps {
        sh './deploy.sh'
      }
    }
  }
}